### ISSUE TITLE
tables are not fetched?

### ISSUE THREAD

**Issue by vesper8** [dmitry-ivanov/laravel-wikipedia-grabber#7]
I want to get tables so I can parse them.

On this page for example

https://en.wikipedia.org/wiki/2019_Australian_Open#Day-by-day_summaries

In the Day-by-day-summaries

The tables contain the "matches" are not fetched at all. 

Is this a limitation of the api or is this library somehow ignoring tables?

If the latter, how can I modify it so that tables are retrieved?

Thanks!

**Comment by vesper8** [comment]
So I've been debugging.. I can confirm that all the data is returned from the API.

I can also confirm that the wikitables gets stripped as a result of this line

```
$sections = (new SectionsParser($title, $body))->sections();
```

That is, if I comment out this line then the tables are not removed. I'm still trying to understand why exactly this is happening

**Comment by dmitry-ivanov** [comment]
It looks like Wikipedia responding in such a way for that page (yeah, it happens for some pages).

You can check the pure Wiki response by this query:
https://en.wikipedia.org/w/api.php?action=query&format=json&formatversion=2&redirects=1&prop=extracts&exlimit=1&explaintext=1&exsectionformat=wiki&titles=2019_Australian_Open

Before the sections parsing there is no Matches info as well.

Maybe you see the "day info", which is above the table and consider it as a table contents?

Because I don't see it neither in response, nor in `$body` dump (which is the same).

**Comment by dmitry-ivanov** [comment]
PS: Actually I've seen that tables content is not present in the output from their API many times.

I'm requesting "wiki" format, which is the plain text. Maybe they consider that tables are some kind of rich content, which is NOT the plain text.

**Comment by dmitry-ivanov** [comment]
I use revisions to link sections with the proper images.

The content of the page is taken from the plain "extract", and there is no table data there, unfortunately.

That's why you don't see it in output.
